### PR TITLE
refs #124 ETのモンスター配置を修正

### PR DESCRIPTION
**Pull request by h3poteto**
- [x] 98Fをリヒ3FMVPに変更
- [x] 99Fをリヒ4FMVPに変更
- [x] 56Fにクトルラを追加
- [x] 61Fにグルームを追加

### CODE REVIEW

**Comment by h3poteto** [comment]
他なんかいじる？ボス増やす？
本鯖を元にした候補

- クラーケン
- クトルラ
- グルーム

あとは，ボスではなく通常Mobでマップにわかないモンスターを配置するのはアリかとおもった．

**Comment by rhutaba** [comment]
生体4FのMVPとかどうだろう。
流石に詰め込みすぎはキツイか。

`2221,RANDEL,ランデル=ロレンス,156,413389,0,675396,460620,1,3855,1230,180,156,142,69,212,49,199,55,10,12,1,7,66,1941,180,76,864,480,2153,1,1435,1,1433,1,1415,1,6223,3000,6470,300,6471,200,0,0,512,0,0,0,0,0,0,0,0,0,0,0
2222,FLAMEL,エミュール=プラメール,157,297477,0,614124,421164,1,3723,1602,86,112,138,79,70,80,82,48,10,12,1,7,63,1941,180,76,864,480,1367,1,1228,1,16010,1,16001,1,6223,3000,6470,300,6471,200,0,0,512,0,0,0,0,0,0,0,0,0,0,0
2223,CELIA,セリア=アルデ,152,216532,0,529236,364500,1,2112,2850,74,312,108,78,60,120,139,49,10,12,1,7,68,1941,180,1152,864,480,2853,1,1654,1,1584,1,1557,1,6223,3000,6470,300,6471,200,0,0,512,0,0,0,0,0,0,0,0,0,0,0
2224,CHEN,チェン=リウ,153,342544,0,611496,418860,1,4214,748,125,156,172,84,84,130,92,100,10,12,1,6,81,1941,180,76,768,480,16017,1,1526,1,1528,1,1830,1,6223,3000,6470,300,6471,200,0,0,512,0,0,0,0,0,0,0,0,0,0,0
2225,GERTIE,ガーティー=ウー,155,340661,0,620802,419184,1,3684,707,108,100,211,124,56,50,122,60,10,12,1,6,85,1941,150,76,864,480,13061,1,2747,1,1227,1,1223,1,6223,3000,6470,300,6471,200,0,0,512,0,0,0,0,0,0,0,0,0,0,0
2226,ALPHOCCIO,アルフォシオ=バジル,154,254430,0,568584,394056,1,3227,2276,84,115,176,180,70,180,193,130,10,12,1,7,64,1941,180,76,864,480,2616,1,18111,1,1913,1,1930,1,6223,3000,6470,300,6471,200,0,0,512,0,0,0,0,0,0,0,0,0,0,0
2227,TRENTINI,トレンティーニ,154,253544,0,568494,394560,2,3270,2306,70,112,176,180,64,195,193,130,10,12,1,7,64,1941,180,76,864,480,2465,1,1985,1,1984,1,1963,1,6223,3000,6470,300,6471,200,0,0,512,0,0,0,0,0,0,0,0,0,0,0
2228,G_RANDEL,ランデル=ロレンス,150,2219167,0,0,0,1,7537,3017,667,151,303,110,212,65,199,52,10,12,1,7,86,1973,100,76,864,480,512,0,512,0,6469,500,6470,300,6471,300,12623,10,6223,10,617,10,512,0,0,0,0,0,0,0,0,0,0,0
2229,G_FLAMEL,エミュール=プラメール,150,1943125,0,0,0,1,7355,2514,253,113,275,73,162,35,136,60,10,12,1,7,83,1973,100,76,864,480,512,0,512,0,6469,500,6470,300,6471,300,12623,10,6223,10,617,10,512,0,0,0,0,0,0,0,0,0,0,0
2230,G_CELIA,セリア=アルデ,150,1687633,0,0,0,1,5481,6114,201,543,165,89,42,223,178,93,10,12,1,7,68,1973,100,1152,864,480,512,0,512,0,6469,500,6470,300,6471,300,12623,10,6223,10,617,10,512,0,0,0,0,0,0,0,0,0,0,0
2231,G_CHEN,チェン=リウ,150,1863750,0,0,0,1,8117,1947,216,134,172,84,64,182,192,100,10,12,1,7,81,1973,100,76,768,480,512,0,512,0,6469,500,6470,300,6471,300,12623,10,6223,10,617,10,512,0,0,0,0,0,0,0,0,0,0,0
2232,G_GERTIE,ガーティー=ウー,150,1779508,0,0,0,1,7161,1274,251,107,211,181,62,37,220,60,10,12,1,7,85,1973,100,76,864,480,512,0,512,0,6469,500,6470,300,6471,300,12623,10,6223,10,617,10,512,0,0,0,0,0,0,0,0,0,0,0
2233,G_ALPHOCCIO,アルフォシオ=バジル,150,1708017,0,0,0,1,6641,4749,201,109,176,180,39,67,193,130,10,12,1,7,84,1973,100,76,864,480,512,0,512,0,6469,500,6470,300,6471,300,12623,10,6223,10,617,10,512,0,0,0,0,0,0,0,0,0,0,0
2234,G_TRENTINI,トレンティーニ,150,1708017,0,0,0,2,6016,4936,181,112,176,180,39,67,193,130,10,12,1,7,84,1973,100,76,864,480,512,0,512,0,6469,500,6470,300,6471,300,12623,10,6223,10,617,10,512,0,0,0,0,0,0,0,0,0,0,0
2235,B_RANDEL,ランデル=ロレンス,160,5725000,0,654015,296468,1,7537,3017,667,151,303,110,212,65,199,52,10,12,1,7,86,1973,100,76,864,480,12623,9000,616,9000,6224,9000,13062,5000,2160,5000,1490,5000,0,0,0,0,0,0,0,0,327007,10000,617,5500,12590,1000,732,450
2236,B_FLAMEL,エミュール=プラメール,160,3525000,0,433329,197776,1,7355,2514,253,113,275,73,162,35,136,60,10,12,1,7,83,1973,100,76,864,480,12623,9000,616,9000,6223,9000,1387,5000,1392,5000,1393,5000,0,0,0,0,0,0,0,0,216664,10000,617,5500,12590,1000,732,450
2237,B_CELIA,セリア=アルデ,160,3206503,0,403206,185920,1,5481,6114,201,543,165,89,42,223,178,93,10,12,1,7,68,1973,100,1152,864,480,12623,9000,616,9000,6224,9000,2854,5000,1584,5000,2582,5000,1140,5000,0,0,0,0,0,0,201603,10000,617,5500,12590,1000,732,450
2238,B_CHEN,チェン=リウ,160,3541125,0,435138,198752,1,8117,1947,216,134,172,84,64,182,192,100,10,12,1,7,81,1973,100,1152,768,480,12623,9000,616,9000,6223,9000,1285,5000,1813,5000,16017,5000,0,0,0,0,0,0,0,0,217569,10000,617,5500,12590,1000,732,450
2239,B_GERTIE,ガーティー=ウー,160,3381066,0,417501,189468,1,7161,1274,251,107,211,181,62,37,220,60,10,12,1,7,85,1973,100,76,864,480,12623,9000,616,9000,6224,9000,13069,5000,13070,5000,1291,5000,0,0,0,0,0,0,0,0,208750,10000,617,5500,12590,1000,732,450
2240,B_ALPHOCCIO,アルフォシオ=バジル,160,3245232,0,406875,187368,1,6641,4749,201,109,176,180,39,67,193,130,10,12,1,7,84,1973,100,76,864,480,12623,9000,616,9000,6223,9000,18103,5000,1290,5000,1913,5000,0,0,0,0,0,0,0,0,203437,10000,617,5500,12590,1000,732,450
2241,B_TRENTINI,トレンティーニ,160,3245232,0,406437,186784,2,6016,4936,181,112,176,180,39,67,193,130,10,12,1,7,84,1973,100,76,864,480,12623,9000,616,9000,6224,9000,18103,5000,18110,5000,1963,5000,0,0,0,0,0,0,0,0,203218,10000,617,5500,12590,1000,732,450
`

**Comment by h3poteto** [comment]
4Fは結構新しい仕様なので相当なきつさになるかと．
ましてやMVPとなると，あいつらMHP3.5MとかでADSとか阿修羅打ってくるんだぜ？
少なくとも98Fよりきつくなるぞｗｗｗ

**Comment by rhutaba** [comment]
99Fが雑魚くて拍子抜けじゃない？生体3FのMOBを4Fに置き換えて地獄をつくるのはどうだろうかｗ

`	setarray 'mob[23][0],	// 99F
		1639,2,		// カトリーヌ=ケイロン
		1634,2,		// セイレン=ウィンザー
		1637,2,		// マーガレッタ=ソリン
		1635,2,		// エレメス=ガイル
		1636,2,		// ハワード=アルトアイゼン
		1638,2,		// セシル=ディモン
		1918,5,		// モロクの現身(天使型)
		1919,5,		// モロクの現身(物質型)
		1920,5,		// モロクの現身(人間型)
		1921,5,		// モロクの現身(精霊型)
		1765,5,		// ランドグリスゴースト
		1755,10,	// スケゴルト(青)
		1754,10,	// スケゴルト(茶)
		1634,15,	// セイレン=ウィンザー
		1268,10,	// ブラッディナイト
		1219,10,	// 深淵の騎士
		1208,10,	// 彷徨う者
		1829,15,	// ソードガーディアン
		1830,15,	// ボウガーディアン
		1639,15,	// カトリーヌ=ケイロン
		1377,10,	// エルダー
		1657,10,	// ラウレル=ヴィンダー
		1263,10,	// ウィンドゴースト
		1140,10,	// マルドゥーク
		1638,10,	// セシル=ディモン
		1830,10,	// ボウガーディアン
		1656,30,	// カヴァク=イカルス
		1702,10,	// 執行する者
		1703,10,	// 慰める者
		1371,10,	// フェイクエンジェル
	;`

**Comment by h3poteto** [comment]
うーん，99Fって今どっちかっていうとザコ敵多めなんだよねー．もちろんそこに生体4Fの通常Mobを混ぜるのはアリだけど，手応えという意味では98Fには勝てないと思う．
いっそ，
98: 生体3FMVPシリーズ
99: 生体4FMVPシリーズ
とかにしたらどうだろう．

**Comment by h3poteto** [comment]
あと，クラーケンはどうかと思うけど，クトルラ・グルームはどっかに配置してあげたい．仲間はずれ良くない．

**Comment by rhutaba** [comment]
階層と難易度を無視できるなら、55Fクトルラ、61Fグルームなんだよね。
灰ワープ後にしたいなら、適当にボスいない階層に混ぜ込んじゃうでいいと思う。

```
	setarray 'mob[5][0],	// 56F
		1319,10,	// フリーズタートル
		1515,10,	// ハティーベベ
		1777,15,	// アイスタイタン
		1775,10,	// スノウアー
		1778,10,	// ゲイズティ
	;
```

```
	setarray 'mob[10][0],	// 61F
		1769,10,	// アガヴ
		1770,10,	// エキオ
		1772,5,		// アイシラ
		1313,10,	// チンピラ
		1154,10,	// パサナ
		1771,5,		// ヴァンベルク
	;
```

**Comment by h3poteto** [comment]
うーん，50層超えてるしいいんじゃないかな．混ぜよう．

**Comment by h3poteto** [comment]
リヒみたいな戦略や戦術で倒す系は楽しいから多少きつくなってもいいんだけど，100のエントヴァイエンは頭良くないし，作業ゲーになるしマジつまらんと思った．

**Pull request merged**
